#Get the list of transactions
GET http://localhost:5084/foods
###

#Get an specific transactions
GET http://localhost:5084/foods/3
###

//Insert transactions
POST http://localhost:5084/foods
Content-Type: application/json

{
    "Name": "Ice cream Chocolate",
    "Brand": "Savory",
    "CategoryID": 5
}

###
PUT http://localhost:5084/foods/3
Content-Type: application/json

{
    "Name": "Broccoli",
    "Brand": "Local",
    "CategoryID": 3
}

###
DELETE http://localhost:5084/foods/3
Content-Type: application/json
